I77 edit institution modal
codersforcauses/wadl pull request #101
Opened 2022-12-17 06:40 UTC by Ch3ngL0rd

## Change Summary
Created a modal.

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [x] The pull request title has an issue number
- [x] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
**[Is there anything in particular in the review that I should be aware of?]**
Have not made it into a component yet.

2022-12-17 13:31 UTC, ChantelleKerr commented on pages/admin/institutions.vue
> +};
Rather than passing three paraments, you could instead pass the whole insitution object

2022-12-17 13:32 UTC, ChantelleKerr commented on pages/admin/institutions.vue
> +  </div>
Make this into it's own component :)

2022-12-17 13:36 UTC, ChantelleKerr commented on pages/admin/institutions.vue
> +              inst.name.slice(0, Math.min(3, inst.name.length))
you can just pass in the whole inst object

2022-12-17 13:39 UTC, ChantelleKerr requested changes
It's looking good. Well done . Some small changes :)

2022-12-19 02:06 UTC, ChantelleKerr requested changes
Please removed package-lock.json. I'm not sure how this got into main

2023-01-07 04:50 UTC, Ch3ngL0rd commented
🥹 pretty pls merge my pull request

2023-01-08 13:04 UTC, ChantelleKerr requested changes
Looks very clean now! One small change

2023-01-08 13:05 UTC, ChantelleKerr requested changes
Looks good! One small change

2023-01-08 13:05 UTC, ChantelleKerr commented on pages/admin/institutions.vue
>  import Modal from "../../components/Modal/Modal.vue";
You don't need to import the component, it should do it automatically

2023-01-08 15:21 UTC, merged