I9 create team registration form component
codersforcauses/wadl pull request #155
Opened 2023-01-14 13:19 UTC by nicodeas

## Change Summary
Team registration modal
bugfixes
added smoother animations

2023-01-15 03:18 UTC, domcain approved these changes

2023-01-15 07:24 UTC, ChantelleKerr requested changes
Hey Nick, great job! you just missed a few input fields and theres some UI changes.
Please do these and fix merge conflicts. 
Thanks :D

2023-01-15 07:24 UTC, ChantelleKerr commented on pages/coordinator.vue
> +        <label class="heading-montserrat">Level</label>
You are missing notes and timeslot

2023-01-15 07:24 UTC, ChantelleKerr commented on pages/coordinator.vue
> +      <hr class="mx-8 h-0.5 bg-slate-500 my-1 border-0" />
Just need to keep mx-8 and the y-padding on the hr tag. It could have more y-padding though, you need to give the element some breathing space because it looks to cramped XD

2023-01-15 07:24 UTC, ChantelleKerr commented on pages/coordinator.vue
> +      />
This button is huge. Just pass size="large" as a prop. It could do with a little extra margin-y

2023-01-15 07:45 UTC, nicodeas commented on pages/coordinator.vue
> +        <label class="heading-montserrat">Level</label>
i followed the picture in the issue; okay

2023-01-16 00:58 UTC, ChantelleKerr commented on pages/coordinator.vue
> +        <label class="heading-montserrat">Level</label>
It's been updated since then on figma. Check figma for the most up to date design as I have direct contact with Keeley on there :D

2023-01-16 00:59 UTC, nicodeas commented on pages/coordinator.vue
> +        <label class="heading-montserrat">Level</label>
Yessir

2023-01-16 01:33 UTC, ChantelleKerr commented on pages/coordinator.vue
> +        <label class="heading-montserrat">Level</label>
thanks boss

2023-01-16 03:33 UTC, rezbyte requested changes
Looking great so far Nick!
I've added some comments to consider.

2023-01-16 03:33 UTC, rezbyte commented on components/Chip/index.vue
> +      @click.prevent="
```suggestion
      @click.stop="
```
Would using [`v-on.stop`](https://vuejs.org/api/built-in-directives.html#v-on) instead of calling `stopPropagation()` not work?

2023-01-16 03:33 UTC, rezbyte commented on components/Multiselect/index.vue
> +  transform: translateY(-20px);
Tailwind has built in utilities for [transitions](https://tailwindcss.com/docs/transition-property) & [transformations](https://tailwindcss.com/docs/translate).

A `ctrl+f` search couldn't find where these are used.
Are they still needed?

2023-01-16 03:33 UTC, rezbyte commented on pages/coordinator.vue
> +  // TODO:
```suggestion
  // TODO:
```
IMO these belong in the GitHub issues rather than the source code.

2023-01-16 07:43 UTC, ChantelleKerr requested changes
One more change. Please check figma for latest design. Timeslot to not be in modal form anymore but keep in form object with default 5.15pm for novice, 6.15pm for junior and 7.15pm for senior

2023-01-16 07:43 UTC, ChantelleKerr commented on pages/coordinator.vue
> +        </div>
Needs to be Week Preference after these form fields. It is a drop down with Week1, Week 2 and Either. Check figma for latest design (Updated today!)

2023-01-17 08:21 UTC, ChantelleKerr commented on components/Multiselect/index.vue
> +  transform: translateY(-20px);
It's used for the dropdown transition on the list

2023-01-17 11:03 UTC, ChantelleKerr commented on pages/coordinator.vue
> +  // TODO:
Leaving it in to help backend connect firebase

2023-01-18 10:23 UTC, domcain approved these changes
Wowza

2023-01-18 10:27 UTC, merged