I231 fill in the rest of the team coordinator pages
codersforcauses/wadl pull request #244
Opened 2023-02-04 06:45 UTC by benvarian

## Change Summary
**[Briefly summarise the changes that you made. Just high-level stuff]**
- add change password functionality for team coordinator and fix the hamburger menu

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [x] The pull request title has an issue number
- [ ] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
**[Is there anything in particular in the review that I should be aware of?]**

2023-02-04 07:08 UTC, rezbyte requested changes
Well done Ben!
I've added some points to consider before merging.

2023-02-04 07:08 UTC, rezbyte commented on pages/coordinator/userinformation.vue
> +  if (passwordForm.value.currentPassword.length < 8) {
These checks are identical to the ones in `signup.vue`.
Perhaps extracting these into a [composable](https://vuejs.org/guide/reusability/composables.html#composables) would be more reusable.

2023-02-04 07:08 UTC, rezbyte commented on pages/coordinator/userinformation.vue
> +const notificationVisibility = ref(false);
```suggestion
const notification = useNotification();
```
I recommend putting the `useNotification` composable here.

2023-02-04 07:08 UTC, rezbyte commented on pages/coordinator/userinformation.vue
> +  infoForm.value = null;
This should be done by Vue automatically.

2023-02-04 07:08 UTC, rezbyte commented on pages/coordinator/userinformation.vue
> +const infoForm = ref({
```suggestion
const infoForm = reactive({
```
The Vue team recommends using [`reactive()`](https://vuejs.org/api/reactivity-core.html#reactive) for objects instead of `ref()`.

2023-02-04 08:26 UTC, benvarian commented on stores/user.js
> +            .catch((error) => {
these functions are all using catch statements?

2023-02-04 08:26 UTC, benvarian commented on stores/user.js
> +      errorCode: "",
?

2023-02-04 09:15 UTC, rezbyte commented on stores/user.js
> +            .catch((error) => {
But they shouldn't be. Let the functions throw errors and catch them in the pages, components etc.

2023-02-04 09:16 UTC, rezbyte commented on stores/user.js
> +      errorCode: "",
Throw an error and use try-catch blocks instead of using a variable to report errors.

2023-02-04 09:18 UTC, benvarian commented on pages/coordinator/userinformation.vue
> +const infoForm = ref({
If we change ref to reactive here is there a specific reason we aren't doing it on all the others refs in the website?

2023-02-04 09:19 UTC, benvarian commented on stores/user.js
> +              this.successCode = "Please re-login with the new password!";
The point of notifying the user if to let them know that they are gonna get signed out and to re-login, otherwise the user won't know what's going on??

2023-02-04 09:29 UTC, rezbyte commented on stores/user.js
> +              this.successCode = "Please re-login with the new password!";
You should definitely notify the user but not in this function.
Functions should have only one purpose (the S in SOLID).
Currently this function has two: 1. to update the password 2. to notify the user upon completition.
Instead notify the user in the calling function i.e.:
```js
async callingFunction() {
  try {
    await updateuserPassword(someValue)
  } catch (error) {
    console.error(error);
    return;
  }
  console.log("Please re-login with the new password!");
}
```

2023-02-04 09:32 UTC, rezbyte commented on pages/coordinator/userinformation.vue
> +const infoForm = ref({
No reason, I thought I would point it out for future PRs.
You don't have to change it if you don't want to.
I've just noticed that much of the website does it despite it not being correct.

2023-02-06 03:20 UTC, benvarian commented on pages/coordinator/userinformation.vue
> +const notificationVisibility = ref(false);
wheres the useNotification compoasble defined and used?

2023-02-06 04:03 UTC, rezbyte commented on pages/coordinator/userinformation.vue
> +const notificationVisibility = ref(false);
It is defined in `composables/useNotification.js`.
See `pages/admin/teams.vue` for an example of usage.

2023-02-06 08:36 UTC, benvarian commented on pages/coordinator/userinformation.vue
> +  if (passwordForm.value.currentPassword.length < 8) {
well worry about this part later i think, everything else has been done tho

2023-02-06 08:37 UTC, benvarian commented
could u please re-review this pr has i think everything works as intended now

2023-02-07 13:35 UTC, rezbyte approved these changes
Great job, Ben!
Approved. :+1:

2023-02-07 14:12 UTC, merged