I172 manage tournament page
codersforcauses/wadl pull request #246
Opened 2023-02-04 07:20 UTC by Theresa-Nadia

## Change Summary
Dynamic routes is set up for the manage tournament page. The url will be specific based on its ID. Only the first row of the page (Registered Teams) is complete. The other parts of the page is still pending, and therefore is commented out. 

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [x] The pull request title has an issue number
- [x] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
The other parts of the page except for "Registered Teams" is commented out as it is not finalized yet

2023-02-04 07:50 UTC, benvarian commented on pages/admin.vue
> +//   middleware: ["admin"],
un comment this so not everyone can access admin page

2023-02-04 07:54 UTC, benvarian commented on pages/admin/tournaments/index.vue
> +
get rid of the try statement for onMounted instead

2023-02-04 07:55 UTC, benvarian commented on pages/admin/tournaments/index.vue
> +  <SearchBar
center the search bar and add the add button next to it

2023-02-04 07:55 UTC, benvarian commented on pages/admin/tournaments/index.vue
> +      @get-id="handleId"
make it so when clickin the edit button, the modal comes up and not the torni info page

2023-02-05 01:53 UTC, ChantelleKerr requested changes
Looking good guys, some more requested changes :)

2023-02-05 01:53 UTC, ChantelleKerr commented on components/Frame.vue
> +      </div>
This could be done using a v-for, You can emit back the button text and then handle navigation from the parent based on button text.

2023-02-05 01:53 UTC, ChantelleKerr commented on components/Frame.vue
> +]);
Could just be one emit that passes a parameter of the button text

2023-02-05 01:53 UTC, ChantelleKerr commented on components/Table.vue
> +              <button @click.prevent="handleEmit(row)">
The table has changed quite a lot from a recent update. Make sure you understand how the new one works and update accordingly

2023-02-05 01:53 UTC, ChantelleKerr commented on pages/admin/tournaments/[tournamentId].vue
> +            }
Change to using one emit

2023-02-05 01:53 UTC, ChantelleKerr commented on components/Frame.vue
> +      :class="
Change to rounded-md so that its consistent with our other border radius'

2023-02-08 11:55 UTC, carrrmenleong commented on pages/admin/tournaments/[tournamentId].vue
> +            }
donee

2023-02-08 11:55 UTC, carrrmenleong commented on components/Frame.vue
> +      </div>
donee

2023-02-09 00:06 UTC, ChantelleKerr approved these changes
Nice work team! It looks really good! :D

2023-02-09 02:28 UTC, merged