I173 add delete buttons
codersforcauses/wadl pull request #247
Opened 2023-02-04 07:25 UTC by domcain

## Change Summary
**[Briefly summarise the changes that you made. Just high-level stuff]**
- delete button functionality added to tournaments, venues and institutions
- delete button adaptive positioning fixed

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [X] The pull request title has an issue number
- [X] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
**[Is there anything in particular in the review that I should be aware of?]**

2023-02-04 07:49 UTC, rezbyte requested changes
Looks good Dom!
Found some typos to fix.
It might also be worth adding notifications.

2023-02-04 07:49 UTC, rezbyte commented on pages/admin/institutions.vue
> +            class=""
```suggestion
```

2023-02-04 07:49 UTC, rezbyte commented on stores/institutions.js
> +    async deleteInstitution(id) {
```suggestion
    deleteInstitution(id) {
```
This doesn't use `await` so no need to make it async.

2023-02-04 07:49 UTC, rezbyte commented on stores/tournaments.js
> +    async deleteTournament(id) {
```suggestion
    deleteTournament(id) {
```
`async` not needed.

2023-02-04 07:49 UTC, rezbyte commented on stores/venues.js
> +    async deleteVenue(id) {
```suggestion
   deleteVenue(id) {
```

2023-02-04 07:49 UTC, rezbyte commented on pages/admin/venues.vue
> +            class=""
```suggestion
```

2023-02-04 07:49 UTC, rezbyte commented on pages/admin/tournaments.vue
> +            class=""
```suggestion
```

2023-02-10 10:45 UTC, domcain commented
@rezbyte  I have added notifications upon successful deletion of venues, institutions and tournaments

2023-02-10 11:05 UTC, rezbyte commented
> @rezbyte I have added notifications upon successful deletion of venues, institutions and tournaments. Will fix the merge conflicts, then make another PR

Nice job!
Although there's no need to write your own code to control the notifications.
The `useNotification` composable implements everything for you.
See `pages/admin/teams.vue` for a usage example.
I'm happy to help if you'd like.

2023-02-11 06:59 UTC, rezbyte submitted a review, later dismissed
Great job, Dom! 🎆 
As discussed, it'll be refactored to use `useNotification` in another PR.

2023-02-15 02:25 UTC, rezbyte approved these changes
I merged `development` into this branch, just re-approving it to please GitHub.

2023-02-15 08:07 UTC, merged