I257 Fixed Institution Page Bugs
codersforcauses/wadl pull request #264
Opened 2023-02-08 05:29 UTC by rezbyte

## Change Summary
- Fixed the institutions duplicating when leaving the institutions page & entering again
- Fixed the institutions edit modal not loading the institution's `code`

### Change Form
- [x] The pull request title has an issue number
- [x] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
I'm not sure whether the `code` field in the institutions are meant to be optional or not.

2023-02-08 07:41 UTC, ChantelleKerr requested changes
Hey jamie nice spot, but you didnt handle everything from the issue. 

They want to be able to make updates to an institution that doesn't have a code so the code should not be a required field. It is a problem with the formfield.

2023-02-08 07:41 UTC, ChantelleKerr commented on stores/institutions.js
> +      this.institutions = [];
For some reason having this breaks the drop down menu on team coordinator when they first setup their institution. The list doesnt display when I comment it out it works fine, I dont understand why ahah. Tested using (tc@tc.com account)

2023-02-08 07:41 UTC, ChantelleKerr commented on stores/institutions.js
> +          code: institution.code,
This causes problems for adding a new institution profile from the team coordinator, it doesnt add it to the database. But good spot it's definitely needed for the admin view.

2023-02-10 12:59 UTC, rezbyte commented on stores/institutions.js
> +      this.institutions = [];
This should be fixed now. :slightly_smiling_face:

2023-02-10 13:05 UTC, rezbyte commented on stores/institutions.js
> +          code: institution.code,
As far as I can see, this function (`createInstitution()`) isn't used in the team coordinator institutions page.
If its going to be added in the future, you could pass in the value with an undefined `code` field.
This would add the institution to the database without the code.

2023-02-10 13:19 UTC, ChantelleKerr commented on stores/institutions.js
> +          code: institution.code,
coordinator/institutions.vue calls checkInsititution which calls createInstitution

2023-02-11 04:07 UTC, rezbyte commented on stores/institutions.js
> +          code: institution.code,
I've added a line to make sure `code` is undefined before calling `checkInstitiution`.

2023-02-12 04:26 UTC, ChantelleKerr requested changes
Something has broken the team coordinator school name selection dropdown, if a school thats already in the dropdown has been clicked it shouldnt be creating a new institution. It should only update the user profile with that institution id

<img width="733" alt="Screen Shot 2023-02-12 at 12 11 33 pm" src="https://user-images.githubusercontent.com/45170409/218292853-a8e5d848-8f3f-489a-9c2f-ddef3b46eacf.png">

This bug that was in the original issue has still not been fixed. If code doesn't exist it should not be a required field when trying to update other fields.

<img width="589" alt="Screen Shot 2023-02-12 at 12 21 34 pm" src="https://user-images.githubusercontent.com/45170409/218292854-a2e9c7d1-a46f-4d71-bc30-27f5345ec4c7.png">

Please try stick to whats been asked in the issue.

2023-02-21 01:26 UTC, ChantelleKerr approved these changes
Looks good! Thanks Jamie and goodluck in Germany! :D

2023-02-21 08:02 UTC, merged