I8 create navbar component
codersforcauses/wadl pull request #27
Opened 2022-12-03 07:46 UTC by LemonTheSour

## Change Summary
-Implemented a basic NavBar component with a Home and Login button. Both buttons just link to the index page at present. 
-Added a logos file to assets with several of the logos in various colours.
-Updated default.vue in layout to display NavBar across all pages by default. 

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [x] The pull request title has an issue number
- [x] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
**[Is there anything in particular in the review that I should be aware of?]**

2022-12-03 11:32 UTC, ChantelleKerr commented on components/NavBar/NavBar.vue
> +  <span class="bg-gold shadow flex position:relative place-items-center">
span should be changed to <nav>

2022-12-03 12:28 UTC, ChantelleKerr commented on components/NavBar/LoginButton.vue
> +};
You should use the composition API - Add setup to the script element and remove export default
https://vuejs.org/guide/extras/composition-api-faq.html#what-is-composition-api

You can handle props by using the defineprops function
https://vuejs.org/api/sfc-script-setup.html#defineprops-defineemits

2022-12-03 12:30 UTC, ChantelleKerr commented on components/NavBar/NavBar.vue
> +};
Please change this to using the composition API. 
The onClick function can be removed as it's not used.

2022-12-03 12:30 UTC, ChantelleKerr commented on components/NavBar/HomeButton.vue
> +</script>
This can be removed

2022-12-03 12:32 UTC, ChantelleKerr commented on pages/index.vue
> +</script>
remove the export default and change script to use setup :)

2022-12-03 12:36 UTC, ChantelleKerr requested changes
Hi Michael, great job so far! I love that you broke up the navbar into different components and also used a correct folder structure. 
I have requested some small changes and I recommend looking up the composition API (I've provided some links)
Committee has also decided that we will not be using typescript so replace lang="ts" with setup.

It looks great btw!

2022-12-04 11:05 UTC, ChantelleKerr commented on components/NavBar/LoginButton.vue
> +    <button class="text-3xl">{{ buttonText }}</button>
It looks better with text-2xl

2022-12-04 11:06 UTC, ChantelleKerr commented on components/NavBar/NavBar.vue
> +    <LoginButton class="absolute right-3" button-text="Login" />
Change button-text to buttonText. We need to stay consistent by using camelCase :)

2022-12-04 11:08 UTC, ChantelleKerr requested changes
Thanks for doing the changes. I missed a few minor things in the previous PR review. Once those are fixed I can merge into main :D

2022-12-04 12:24 UTC, ChantelleKerr commented on components/NavBar/NavBar.vue
> +    <LoginButton class="absolute right-3" button-text="Login" />
Did this get done? @LemonTheSour

2022-12-04 13:32 UTC, LemonTheSour commented on components/NavBar/NavBar.vue
> +    <LoginButton class="absolute right-3" button-text="Login" />
Just pushed up now

2022-12-04 13:42 UTC, ChantelleKerr approved these changes
Good job! It looks amazing :D

2022-12-04 13:42 UTC, merged