I75 create fixtures page
codersforcauses/wadl pull request #281
Opened 2023-02-18 06:57 UTC by DataScientistDave

## Change Summary

- Used dynamic routes to create the fixtures page for each tournament. 
- Added the dynamic routes for each fixtures page to the public routes in the middleware.
- The fixtures page generates a table after a round and level is selected.
- The columns of the table are Div, Venue, Date, Time, Affirmative Team, Negative Team, Topic and Status.

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [x] The pull request title has an issue number
- [x] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information

2023-02-21 01:49 UTC, ChantelleKerr requested changes
Hey Nisarg, everything looks really good! Ij ust need one line changed :D
Thanks for all your work on this, amazing stuff.

2023-02-21 01:49 UTC, ChantelleKerr commented on pages/fixtures/[tournamentId].vue
> +  roundSelected = undefined;
It should load the current round as well when changing levels :)

2023-02-22 11:03 UTC, DataScientistDave commented on pages/fixtures/[tournamentId].vue
> +  roundSelected = undefined;
Should be working now.

2023-02-23 05:38 UTC, ChantelleKerr approved these changes
Great job! It looks really good :D

2023-02-23 05:39 UTC, merged