I261 update team coordinator index page
codersforcauses/wadl pull request #283
Opened 2023-02-20 13:59 UTC by orange-my-cat

## Change Summary
**[Briefly summarise the changes that you made. Just high-level stuff]**
On TC login it displays a list of registered competitions, then links to a list of teams from the institution that is registered to the competition.

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [x] The pull request title has an issue number
- [x] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
**[Is there anything in particular in the review that I should be aware of?]**

2023-02-20 15:43 UTC, ChantelleKerr requested changes
Nice work guys. Some small changes.
I have found a few bugs. 
1. When I register for multiple tournaments I can only see the teams from the first tournament I've registered. All the other pages say "No data available" when I click "teams".  I have to refresh to see them (fixed)
2. It seems that if I go to register a second batch of teams at a later stage, it doesnt display in the table however I can see that the teams have been added on the backend. (fixed)
3. In institutions.js on line ~200 (in the where clause) its getting a team count where its only looking for institutionId but it should now be institutionId and tournamentId
4. Teams should be changed to Tournaments in the navbar (fixed)

Please handle merge conflicts, thanks :D

2023-02-20 15:43 UTC, ChantelleKerr commented on pages/coordinator/index.vue
> +  <ProfileInfo username="Sarah Tan" role="Team Coordinator" />
The username should be the logged in users name

2023-02-20 15:43 UTC, ChantelleKerr commented on pages/coordinator/index.vue
> +      class="grid grid-cols-3 justify-between gap-4"
Maybe try using a grid so that its responsive for mobile. small devices should only have one column of tournaments with the rest stacking below it.

2023-02-20 15:43 UTC, ChantelleKerr commented on pages/coordinator/teams/[tournamentId].vue
> +);
Try the title to "Manage Teams" with the tournament name underneath so that its consistent with other pages. <Header /> should have a subtitle prop (if your branch is up to date with development)

2023-02-23 07:27 UTC, orange-my-cat commented
> 3. In institutions.js on line ~200 (in the where clause) its getting a team count where its only looking for institutionId but it should now be institutionId and tournamentId

Does this mean that we can have teams with the same name on different tournaments? Like Team 1 and Team 2 in multiple tournaments?

2023-02-23 08:54 UTC, ChantelleKerr commented
> > 3. In institutions.js on line ~200 (in the where clause) its getting a team count where its only looking for institutionId but it should now be institutionId and tournamentId
> 
> Does this mean that we can have teams with the same name on different tournaments? Like Team 1 and Team 2 in multiple tournaments?

Correct :)

2023-02-25 14:31 UTC, ChantelleKerr approved these changes
Great job! :) 
Thanks for all your help guys!

2023-02-25 14:42 UTC, merged