I7 create home page
codersforcauses/wadl pull request #50
Opened 2022-12-10 04:47 UTC by Theresa-Nadia

## Change Summary
We created a home page as the landing page of the website based on the figma. It dynamically renders buttons based on the input tournaments. 

Updated main.css to import font.

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [x] The pull request title has an issue number
- [x] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
close #7

2022-12-10 05:45 UTC, rezbyte submitted a review, later dismissed
Nice work so far! 🙂 
I've merged the branch with main & run `yarn lint:fix` on your code.
Also added my thoughts about the code in the comments.

2022-12-10 05:45 UTC, rezbyte commented on components/HomePage/LevelButton.vue
> +  buttonText: {
```suggestion
  text: {
```
The 'button' in the prop name is a bit redundant.

2022-12-10 05:45 UTC, rezbyte commented on pages/index.vue
> +  <div id="logo">
```suggestion
```
This div is unnecessary.

2022-12-10 05:45 UTC, rezbyte commented on pages/index.vue
> +  </div>
```suggestion
```

2022-12-10 05:45 UTC, rezbyte commented on pages/index.vue
> +  <div>
```suggestion
```
This div isn't needed either

2022-12-10 05:45 UTC, rezbyte commented on pages/index.vue
> +  </div>
```suggestion
```

2022-12-10 05:45 UTC, rezbyte commented on components/HomePage/LevelButton.vue
> +  <div
```suggestion
  <button
```
It's better to use the correct tags instead of using `div`s for everything.
The tags help screen readers & other assistive technologies operate. 
I recommend using [MDN's HTML elements reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Element).

2022-12-10 05:45 UTC, rezbyte commented on components/HomePage/LevelButton.vue
> +  </div>
```suggestion
  </button>
```

2022-12-10 05:45 UTC, rezbyte commented on pages/index.vue
> +<style setup></style>
```suggestion
```

There doesn't seem to be styling here.

2022-12-10 05:45 UTC, rezbyte commented on pages/index.vue
> +    <div class="grid grid-cols-3 grid-rows-6 gap-6 justify-between">
```suggestion
    <div class="mx-auto h-screen place-items-center justify-center grid grid-cols-3 grid-rows-6 gap-6">
```
This should remove the need for the above `div`.

2022-12-10 05:45 UTC, rezbyte commented on pages/index.vue
> +  <div class="flex h-screen justify-center">
```suggestion
```

2022-12-10 05:45 UTC, rezbyte commented on pages/index.vue
> +  </div>
```suggestion
```

2022-12-10 05:45 UTC, rezbyte commented on pages/index.vue
> +      <div v-for="item in tournaments" :key="item" class="">
```suggestion
      <div v-for="item in tournaments" :key="item">
```
The `class` attribute is empty.

2022-12-10 05:45 UTC, rezbyte commented on pages/index.vue
> +          <LevelButton :buttonText="item" />
```suggestion
          <LevelButton :text="item" />
```

2022-12-10 05:57 UTC, ChantelleKerr commented on assets/css/main.css
> +@import url("https://fonts.googleapis.com/css?family=Montserrat");
You don't need to import this its already defined in the tailwind config

2022-12-10 05:59 UTC, ChantelleKerr commented on components/HomePage/LevelButton.vue
> +    class="bg-gradient-to-r from-[#A8A8A8] via-[#8A8A8A] to-[#474747] p-2 m-5 w-64 h-20 rounded-2xl flex justify-center place-items-center text-white text-3xl font-montserrat"
I like them plain black :)

2022-12-10 06:01 UTC, ChantelleKerr requested changes
Good job, Theres some other ome small changes that I'd like to add :)

2022-12-10 07:03 UTC, ChantelleKerr commented on pages/index.vue
> +<style setup></style>
This still needs to be done

2022-12-10 07:05 UTC, ChantelleKerr commented on components/HomePage/LevelButton.vue
> +  <div
This still needs to be changed to a button tag

2022-12-10 07:07 UTC, ChantelleKerr commented on pages/index.vue
> +  <index titleText="Competitions" />
You can just use <  Header title-text="Competitions"/> You don't need to import it as well :) You can look at `components.vue` for an example on how to use it

2022-12-10 07:08 UTC, ChantelleKerr requested changes
Almost there :)

2022-12-11 01:23 UTC, ChantelleKerr commented on pages/index.vue
> +  >
You can add a margin top to the div instead of using the br tag

2022-12-11 01:23 UTC, ChantelleKerr requested changes
Sorry one more thing

2022-12-12 12:35 UTC, merged