I38 create manage institution page
codersforcauses/wadl pull request #59
Opened 2022-12-10 07:19 UTC by Ch3ngL0rd

## Change Summary
Created the manage institution page - copied a lot off the "adjudicators page"

### Change Form
- [x] The pull request title has an issue number
- [x] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
**[Is there anything in particular in the review that I should be aware of?]**
closes #38

2022-12-10 07:26 UTC, ChantelleKerr commented on pages/manageinstitutions.vue
> +<script setup>
change the file name to institutions.vue

2022-12-10 07:27 UTC, ChantelleKerr requested changes
Just a file name change please :) 
Good work !

2022-12-11 00:30 UTC, Ch3ngL0rd commented
Changed file name to 'institutions.vue'

2022-12-11 00:55 UTC, ChantelleKerr approved these changes
Good job :)

2022-12-11 00:55 UTC, merged