I12 super admin page
codersforcauses/wadl pull request #67
Opened 2022-12-10 08:21 UTC by daviid-wang

## Change Summary
Created the page similar to the figma design
Components include: AdminButton and ProfileInfo
Pages: SuperAdminPage

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [x] The pull request title has an issue number
- [x] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
**[Is there anything in particular in the review that I should be aware of?]**

2022-12-11 01:01 UTC, ChantelleKerr commented on components/SuperAdminPage/ProfileInfo.vue
> +    <!-- </div> -->
These comments can be removed :)

2022-12-11 01:03 UTC, ChantelleKerr commented on pages/superAdminPage.vue
> +    import { UserPlusIcon } from "@heroicons/vue/24/outline";
You can import all these on the same line { UserIcon, TrophyIcon, .... , UserPlusIcon }

2022-12-11 01:03 UTC, ChantelleKerr commented on pages/superAdminPage.vue
> +        <ProfileInfo username="Carmen Leong" role="Super Admin"/>
Change Role to just "Admin"

2022-12-11 01:04 UTC, ChantelleKerr commented on pages/superAdminPage.vue
> +    import ProfileInfo from '~/components/SuperAdminPage/ProfileInfo.vue';
Change the file name to just admin.vue

2022-12-11 01:20 UTC, ChantelleKerr requested changes
Great job! It looks really good and I love that you used different components

2022-12-12 03:19 UTC, rezbyte requested changes
Nice work so far! :slightly_smiling_face: 
I'm getting some Vue errors in the terminal when visiting the super admin page.
There's also some linting errors that the workflow didn't pick up.
I'll have to fix the workflow. (Update: #72)
Don't forget to use the automatically generated branches rather than creating your own.
Other than that, keep it up! :+1:

2022-12-12 03:19 UTC, rezbyte commented on components/SuperAdminPage/ProfileInfo.vue
> +    <div class="w-2/3">
```suggestion
    <section class="w-2/3">
```
Semantic HTML over just `div`s is better for accessibility.

2022-12-12 03:19 UTC, rezbyte commented on components/SuperAdminPage/ProfileInfo.vue
> +    </div>
```suggestion
    </section>
```

2022-12-12 03:19 UTC, rezbyte commented on components/SuperAdminPage/ProfileInfo.vue
> +        <div class="ml-8 text-xl">{{role}}</div>
```suggestion
        <p class="ml-8 text-xl">{{role}}</p>
```

2022-12-12 03:19 UTC, rezbyte commented on pages/superAdminPage.vue
> +    <div class="flex items-center justify-center">
I think all of this would be better placed inside the `ProfileInfo` component.

2022-12-12 04:09 UTC, daviid-wang commented
I'll have a look at these tonight, and yeah I forgot to do linting oops

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Jamie Turner ***@***.***>
Sent: Monday, December 12, 2022 11:19:22 AM
To: codersforcauses/wadl ***@***.***>
Cc: David Wang ***@***.***>; Assign ***@***.***>
Subject: Re: [codersforcauses/wadl] I12 super admin page (PR #67)


@rezbyte requested changes on this pull request.

Nice work so far! 🙂
I'm getting some Vue errors in the terminal when visiting the super admin page.
There's also some linting errors that the workflow didn't pick up.
I'll have to fix the workflow.
Other than that, keep it up! 👍

________________________________

In components/SuperAdminPage/AdminButton.vue<https://github.com/codersforcauses/wadl/pull/67#discussion_r1045364862>:

> @@ -0,0 +1,24 @@

+<script setup>

+    const {props} = defineProps({

+        title: String,

+        link: String,

+        icon: String,

+    })

+</script>

+

+<template>

+    <div class="flex items-center justify-self-center">

+        <NuxtLink

+            :to=link



⬇️ Suggested change

-            :to=link

+            :to="link"



________________________________

In components/SuperAdminPage/AdminButton.vue<https://github.com/codersforcauses/wadl/pull/67#discussion_r1045365299>:

> +    const {props} = defineProps({

+        title: String,

+        link: String,

+        icon: String,

+    })

+</script>

+

+<template>

+    <div class="flex items-center justify-self-center">

+        <NuxtLink

+            :to=link

+            data-mdb-ripple="true"

+            data-mdb-ripple-color="light"

+            class="w-64 px-2 py-2 m-5 text-center text-black transition duration-200 ease-in-out shadow-md rounded-xl bg-gold hover:bg-light-gold hover:shadow-lg focus:bg-light-gold focus:shadow-lg focus:outline-none focus:ring-0 active:bg-light-gold active:shadow-lg"

+            >

+            <div class="flex items-center justify-start">



⬇️ Suggested change

-            <div class="flex items-center justify-start">



This div is unnecessary, the styling can be moved to the NuxtLink.

________________________________

In components/SuperAdminPage/AdminButton.vue<https://github.com/codersforcauses/wadl/pull/67#discussion_r1045365362>:

> @@ -0,0 +1,24 @@

+<script setup>

+    const {props} = defineProps({

+        title: String,

+        link: String,

+        icon: String,

+    })

+</script>

+

+<template>

+    <div class="flex items-center justify-self-center">

+        <NuxtLink

+            :to=link

+            data-mdb-ripple="true"

+            data-mdb-ripple-color="light"

+            class="w-64 px-2 py-2 m-5 text-center text-black transition duration-200 ease-in-out shadow-md rounded-xl bg-gold hover:bg-light-gold hover:shadow-lg focus:bg-light-gold focus:shadow-lg focus:outline-none focus:ring-0 active:bg-light-gold active:shadow-lg"



⬇️ Suggested change

-            class="w-64 px-2 py-2 m-5 text-center text-black transition duration-200 ease-in-out shadow-md rounded-xl bg-gold hover:bg-light-gold hover:shadow-lg focus:bg-light-gold focus:shadow-lg focus:outline-none focus:ring-0 active:bg-light-gold active:shadow-lg"

+            class="flex items-center justify-start w-64 px-2 py-2 m-5 text-center text-black transition duration-200 ease-in-out shadow-md rounded-xl bg-gold hover:bg-light-gold hover:shadow-lg focus:bg-light-gold focus:shadow-lg focus:outline-none focus:ring-0 active:bg-light-gold active:shadow-lg"



________________________________

In components/SuperAdminPage/AdminButton.vue<https://github.com/codersforcauses/wadl/pull/67#discussion_r1045365448>:

> +        icon: String,

+    })

+</script>

+

+<template>

+    <div class="flex items-center justify-self-center">

+        <NuxtLink

+            :to=link

+            data-mdb-ripple="true"

+            data-mdb-ripple-color="light"

+            class="w-64 px-2 py-2 m-5 text-center text-black transition duration-200 ease-in-out shadow-md rounded-xl bg-gold hover:bg-light-gold hover:shadow-lg focus:bg-light-gold focus:shadow-lg focus:outline-none focus:ring-0 active:bg-light-gold active:shadow-lg"

+            >

+            <div class="flex items-center justify-start">

+                <component :is="icon" class="w-10 h-10 ml-2 mr-6" />

+                {{ title }}

+            </div>



⬇️ Suggested change

-            </div>



________________________________

In components/SuperAdminPage/ProfileInfo.vue<https://github.com/codersforcauses/wadl/pull/67#discussion_r1045366148>:

> @@ -0,0 +1,18 @@

+<script setup>

+        const {props} = defineProps({

+        username: String,

+        role: String,

+    })

+</script>

+

+<template>

+    <div class="w-2/3">

+        <div class="text-6xl">{{username}}</div>



⬇️ Suggested change

-        <div class="text-6xl">{{username}}</div>

+        <h1 class="text-6xl">{{username}}</h1>



________________________________

In components/SuperAdminPage/ProfileInfo.vue<https://github.com/codersforcauses/wadl/pull/67#discussion_r1045367880>:

> @@ -0,0 +1,18 @@

+<script setup>

+        const {props} = defineProps({

+        username: String,

+        role: String,

+    })

+</script>

+

+<template>

+    <div class="w-2/3">



⬇️ Suggested change

-    <div class="w-2/3">

+    <section class="w-2/3">



Semantic HTML over just divs is better for accessibility.

________________________________

In components/SuperAdminPage/ProfileInfo.vue<https://github.com/codersforcauses/wadl/pull/67#discussion_r1045367921>:

> @@ -0,0 +1,18 @@

+<script setup>

+        const {props} = defineProps({

+        username: String,

+        role: String,

+    })

+</script>

+

+<template>

+    <div class="w-2/3">

+        <div class="text-6xl">{{username}}</div>

+        <div class="ml-8 text-xl">{{role}}</div>

+        <hr class="w-full mt-8 mb-6 border-black border-solid">

+    </div>



⬇️ Suggested change

-    </div>

+    </section>



________________________________

In components/SuperAdminPage/ProfileInfo.vue<https://github.com/codersforcauses/wadl/pull/67#discussion_r1045369371>:

> @@ -0,0 +1,18 @@

+<script setup>

+        const {props} = defineProps({

+        username: String,

+        role: String,

+    })

+</script>

+

+<template>

+    <div class="w-2/3">

+        <div class="text-6xl">{{username}}</div>

+        <div class="ml-8 text-xl">{{role}}</div>



⬇️ Suggested change

-        <div class="ml-8 text-xl">{{role}}</div>

+        <p class="ml-8 text-xl">{{role}}</p>



________________________________

In pages/superAdminPage.vue<https://github.com/codersforcauses/wadl/pull/67#discussion_r1045373448>:

> +    import AdminButton from '~/components/SuperAdminPage/AdminButton.vue';

+    import ProfileInfo from '~/components/SuperAdminPage/ProfileInfo.vue';

+    import { UserIcon } from ***@***.***/vue/24/outline";

+    import { TrophyIcon } from ***@***.***/vue/24/outline";

+    import { BuildingLibraryIcon } from ***@***.***/vue/24/outline";

+    import { ScaleIcon } from ***@***.***/vue/24/outline";

+    import { UserGroupIcon } from ***@***.***/vue/24/outline";

+    import { MapPinIcon } from ***@***.***/vue/24/outline";

+    import { TableCellsIcon } from ***@***.***/vue/24/outline";

+    import { UsersIcon } from ***@***.***/vue/24/outline";

+    import { ClipboardIcon } from ***@***.***/vue/24/outline";

+    import { UserPlusIcon } from ***@***.***/vue/24/outline";

+</script>

+

+<template>

+    <div class="flex items-center justify-center">



I think all of this would be better placed inside the ProfileInfo component.

—
Reply to this email directly, view it on GitHub<https://github.com/codersforcauses/wadl/pull/67#pullrequestreview-1212840999>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AYH4H3LV24LMWMOK4MHYBA3WM2KTVANCNFSM6AAAAAAS2D6B6M>.
You are receiving this because you were assigne [...]

2022-12-13 03:30 UTC, ChantelleKerr approved these changes
Looks good! Great job :)

2022-12-13 03:35 UTC, rezbyte commented
> Looks good! Great job :)

I'll just merge this branch with main to check for linting problems first.

2022-12-13 03:40 UTC, rezbyte approved these changes
Well done! :fireworks: 
Merge when you're ready.

2022-12-13 08:12 UTC, merged