I40 create manage venue page
codersforcauses/wadl pull request #76
Opened 2022-12-13 08:40 UTC by jith4j

## Change Summary
**Made the search-bar more rounded to match the wireframe**

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [x] The pull request title has an issue number
- [ ] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
**[Is there anything in particular in the review that I should be aware of?]**

2022-12-13 08:47 UTC, ChantelleKerr commented on components/Manage-Venue/searchbar.vue
> +<script setup></script>
This file can be removed. We already have a search bar component.

2022-12-13 08:48 UTC, ChantelleKerr commented on components/Manage-Venue/venue.vue
> +    defineProps({
I'm not sure what this file is for?

2022-12-13 08:49 UTC, ChantelleKerr commented on components/SearchBar/index.vue
>        @input="emit('handleFilter', searchString.toLowerCase())"
The reason this is rounded-md is so that the border radius is consistent with the button radius

2022-12-13 08:50 UTC, ChantelleKerr commented on pages/manage-venue.vue
> +<script setup>
Change the file name to venues.vue

2022-12-16 08:48 UTC, ChantelleKerr commented on components/Table/index.vue
> +          >
This text size is too big. It needs to be smaller than the header. Probably use the same size as the insitutions and adjudicator page.

2022-12-16 08:51 UTC, ChantelleKerr commented on data/venues.json
> +  {
jUse id instead of index because its common practice for identifiers.

2022-12-16 08:52 UTC, ChantelleKerr commented on components/Table/index.vue
> +            class="font-montserrat text-2xl py-2"
Size to be smaller

2022-12-16 08:53 UTC, ChantelleKerr commented on nuxt.config.js
> +        },
This can be combined

2022-12-16 08:55 UTC, ChantelleKerr commented on pages/venues.vue
> +    <div class="flex content-center justify-center h-3/5 w-10/12">
You might as well use the extra white space available so use a larger width. I think the adjudicator and insitution page use w-11/12

2022-12-16 08:57 UTC, ChantelleKerr commented on pages/venues.vue
> +    </div>
The button should look the same as adjudicator and insitution page. Bring that div outside the div that it is in currently and use the same classes that adjudicator/insitution use. Consistency is important :)

2022-12-16 08:58 UTC, ChantelleKerr commented on pages/venues.vue
> +      </Modal>
This shouldnt be in the div that the button is in. This should be done in another issue

2022-12-16 09:03 UTC, ChantelleKerr requested changes
Something to work on while waiting for your team :) 
You can also move the venues.vue file into the admin folder then it will be accessed by using admin/venues. You can also link it up on the admin dashboard in admin/index.vue
Nice job so far! This team is putting in a lot of work.

2022-12-16 09:06 UTC, ChantelleKerr commented on pages/venues.vue
> +      <Table :config="config" :venues="venues" />
Instead of config use headers. This not noticable what config is when first looking at it. Headers is more descriptive :)

2022-12-16 09:07 UTC, ChantelleKerr requested changes
Oops one more thing

2022-12-16 10:52 UTC, LemonTheSour commented on nuxt.config.js
> +        },
![Capture](https://user-images.githubusercontent.com/48979069/208082200-74d1748c-e974-4140-a40a-a3854f4b4860.PNG)

This works, but I'm not sure if it's good practice, I'm getting a linting error for having duplicate keys, let me know if it hasn't been fixed properly

2022-12-16 11:19 UTC, ChantelleKerr commented on nuxt.config.js
> +        },
I meant add it to the existing href after Montserrat add &family=Carter+One

2022-12-16 11:25 UTC, ChantelleKerr commented on pages/admin/venues.vue
> +  </div>
Do it like this so that the footer is not big and matches adjudicator :)
```
<div class="flex justify-center">
    <div class="flex content-center justify-center h-3/5 px-2">
      <Table :headers="headers" :venues="venues" />
    </div>
  </div>
  <div class="fixed inset-x-0 bottom-0 w-full bg-white">
    <Button
      button-text="Add Venue"
      button-color="bg-gold"
      class="m-5 ml-8"
      @click="show = !show"
    />
  </div>
  ```

2022-12-16 11:30 UTC, ChantelleKerr commented on pages/admin/venues.vue
> +// };
This could be removed

2022-12-16 11:31 UTC, ChantelleKerr commented on nuxt.config.js
> +          href: "https://fonts.googleapis.com/css2?family=Carter+One&display=swap",
`href: "https://fonts.googleapis.com/css2?family=Jost&family=Lato&family=Montserrat&family=Carter+One&display=swap",`

2022-12-16 11:31 UTC, ChantelleKerr requested changes
Looking really good! Almost there :)

2022-12-17 03:19 UTC, ChantelleKerr approved these changes
Looks good! Great job :)

2022-12-17 03:37 UTC, merged