I63 create sign up requests page
codersforcauses/wadl pull request #81
Opened 2022-12-14 07:03 UTC by Ch3ngL0rd

## Change Summary
Created the sign-up page with basic javascript dummy functions. Added CSS to try and match the Figma file.

### Change Form

- [x] The pull request title has an issue number
- [x] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information

2022-12-14 07:53 UTC, ChantelleKerr commented on pages/signup_requests.vue
> +          </select>
rather than doing selected you can do this `<select v-model="person.role">`

2022-12-14 07:55 UTC, ChantelleKerr commented on data/pretendpeople.json
> +    "role": "Administrator"
Public users wont be able to register as an admin - this is something that that an existing admin will handle. The options are Adjudicator, Adjudicator Coordinator, Team Coordinator.
:)

2022-12-14 08:37 UTC, Ch3ngL0rd commented
All changes done! 😁

2022-12-14 09:00 UTC, ChantelleKerr requested changes
Just a small change and a small warning in the console that a found

2022-12-16 08:32 UTC, ChantelleKerr approved these changes
Good job! Approved :D

2022-12-16 22:58 UTC, merged